import { GLOBAL_FLAGS } from './args';
import type { AnyCommand } from './command';
import { type Inputs, flagOf } from './inputs';
import type { Entry, Group } from './registry';

export type Shell = 'zsh' | 'bash' | 'fish';
export const SHELLS: ReadonlyArray<Shell> = ['zsh', 'bash', 'fish'];

/** A command with the flags its completion needs */
export interface Completable {
  path: string[];
  summary: string;
  flags: Array<{
    name: string;
    description: string;
    values?: ReadonlyArray<string>;
  }>;
}

/** What completion knows: every command loaded once, flags flattened */
export async function collect(entries: Entry[]): Promise<Completable[]> {
  const globals = Object.entries(GLOBAL_FLAGS).map(([name, spec]) => ({
    name,
    description: spec.description
  }));
  return Promise.all(
    entries.map(async (entry) => {
      const command: AnyCommand = await entry.load();
      const own = Object.entries(command.inputs as Inputs).map(
        ([key, spec]) => ({
          name: flagOf(key, spec),
          description: spec.description ?? spec.prompt,
          values: spec.values
        })
      );
      return {
        path: entry.path,
        summary: entry.summary,
        flags: [...own, ...globals]
      };
    })
  );
}

const q = (text: string): string => text.replace(/'/g, "'\\''");
const zshEscape = (text: string): string =>
  text.replace(/[:\\]/g, '\\$&').replace(/'/g, "'\\''");

export function zsh(groups: Group[], commands: Completable[]): string {
  const top = commands.filter((c) => c.path.length === 1);
  const usedGroups = groups.filter((g) =>
    commands.some((c) => c.path[0] === g.name && c.path.length > 1)
  );
  const flagsOf = (c: Completable) =>
    c.flags
      .map((f) =>
        f.values
          ? `'--${f.name}[${zshEscape(f.description)}]:value:(${f.values.join(' ')})'`
          : `'--${f.name}[${zshEscape(f.description)}]'`
      )
      .join(' ');
  const lines = [
    '#compdef cdwr',
    '# Generated by `cdwr completion zsh`',
    '_cdwr() {',
    '  local curcontext="$curcontext" state line',
    '  typeset -A opt_args',
    "  _arguments -C '1:command:->cmd' '2:subcommand:->sub' '*::args:->args'",
    '  case $state in',
    '    cmd)',
    '      local -a items',
    `      items=(${[...usedGroups.map((g) => `'${g.name}:${zshEscape(g.summary)}'`), ...top.map((c) => `'${c.path[0]}:${zshEscape(c.summary)}'`)].join(' ')})`,
    "      _describe -t commands 'cdwr command' items",
    '      ;;',
    '    sub)',
    '      case $line[1] in'
  ];
  for (const group of usedGroups) {
    const own = commands.filter(
      (c) => c.path[0] === group.name && c.path.length > 1
    );
    lines.push(
      `        ${group.name})`,
      '          local -a items',
      `          items=(${own.map((c) => `'${c.path[1]}:${zshEscape(c.summary)}'`).join(' ')})`,
      `          _describe -t commands '${group.name} command' items`,
      '          ;;'
    );
  }
  for (const c of top) {
    lines.push(`        ${c.path[0]}) _arguments ${flagsOf(c)} ;;`);
  }
  lines.push(
    '      esac',
    '      ;;',
    '    args)',
    '      case "$line[1] $line[2]" in'
  );
  for (const c of commands.filter((c) => c.path.length > 1)) {
    lines.push(`        '${c.path.join(' ')}') _arguments ${flagsOf(c)} ;;`);
  }
  for (const c of top) {
    lines.push(`        '${c.path[0]} '*) _arguments ${flagsOf(c)} ;;`);
  }
  lines.push('      esac', '      ;;', '  esac', '}', 'compdef _cdwr cdwr');
  return `${lines.join('\n')}\n`;
}

export function bash(groups: Group[], commands: Completable[]): string {
  const top = commands.filter((c) => c.path.length === 1).map((c) => c.path[0]);
  const usedGroups = groups.filter((g) =>
    commands.some((c) => c.path[0] === g.name && c.path.length > 1)
  );
  const lines = [
    '# Generated by `cdwr completion bash`',
    '_cdwr() {',
    '  local cur="${COMP_WORDS[COMP_CWORD]}" first="${COMP_WORDS[1]}" second="${COMP_WORDS[2]}"',
    '  local words=""',
    '  if [ "$COMP_CWORD" -eq 1 ]; then',
    `    words="${[...usedGroups.map((g) => g.name), ...top].join(' ')}"`,
    '  elif [ "$COMP_CWORD" -eq 2 ]; then',
    '    case "$first" in'
  ];
  for (const group of usedGroups) {
    const own = commands.filter(
      (c) => c.path[0] === group.name && c.path.length > 1
    );
    lines.push(
      `      ${group.name}) words="${own.map((c) => c.path[1]).join(' ')}" ;;`
    );
  }
  for (const c of commands.filter((c) => c.path.length === 1)) {
    lines.push(
      `      ${c.path[0]}) words="${c.flags.map((f) => `--${f.name}`).join(' ')}" ;;`
    );
  }
  lines.push('    esac', '  else', '    case "$first $second" in');
  for (const c of commands.filter((c) => c.path.length > 1)) {
    lines.push(
      `      '${c.path.join(' ')}') words="${c.flags.map((f) => `--${f.name}`).join(' ')}" ;;`
    );
  }
  for (const c of commands.filter((c) => c.path.length === 1)) {
    lines.push(
      `      '${c.path[0]} '*) words="${c.flags.map((f) => `--${f.name}`).join(' ')}" ;;`
    );
  }
  lines.push(
    '    esac',
    '  fi',
    '  COMPREPLY=($(compgen -W "$words" -- "$cur"))',
    '}',
    'complete -F _cdwr cdwr'
  );
  return `${lines.join('\n')}\n`;
}

export function fish(groups: Group[], commands: Completable[]): string {
  const lines = ['# Generated by `cdwr completion fish`'];
  const usedGroups = groups.filter((g) =>
    commands.some((c) => c.path[0] === g.name && c.path.length > 1)
  );
  for (const g of usedGroups) {
    lines.push(
      `complete -c cdwr -n '__fish_use_subcommand' -a ${g.name} -d '${q(g.summary)}'`
    );
  }
  for (const c of commands) {
    const [first, second] = c.path;
    if (second) {
      lines.push(
        `complete -c cdwr -n '__fish_seen_subcommand_from ${first}; and not __fish_seen_subcommand_from ${second}' -a ${second} -d '${q(c.summary)}'`
      );
    } else {
      lines.push(
        `complete -c cdwr -n '__fish_use_subcommand' -a ${first} -d '${q(c.summary)}'`
      );
    }
    const leaf = second ?? first;
    for (const f of c.flags) {
      const values = f.values ? ` -x -a '${f.values.join(' ')}'` : '';
      lines.push(
        `complete -c cdwr -n '__fish_seen_subcommand_from ${leaf}' -l ${f.name} -d '${q(f.description)}'${values}`
      );
    }
  }
  return `${lines.join('\n')}\n`;
}

export const render = (
  shell: Shell,
  groups: Group[],
  commands: Completable[]
): string => ({ zsh, bash, fish })[shell](groups, commands);
