import { completionFile, completionState, normalise } from './completion.logic';

const dirs = { cdwrHome: '/h/.cdwr', home: '/h' };

describe('completionFile', () => {
  it('puts fish in its completions directory', () => {
    expect(completionFile('fish', dirs)).toBe(
      '/h/.config/fish/completions/cdwr.fish'
    );
  });

  it.each(['zsh', 'bash'] as const)('puts %s under cdwr home', (shell) => {
    expect(completionFile(shell, dirs)).toBe(`/h/.cdwr/completion.${shell}`);
  });

  it('follows a custom cdwr home', () => {
    expect(completionFile('zsh', { cdwrHome: '/custom', home: '/h' })).toBe(
      '/custom/completion.zsh'
    );
  });
});

describe('normalise', () => {
  it('drops the header and trailing whitespace', () => {
    expect(normalise('# Generated by cdwr completion zsh\na  \nb\n\n')).toBe(
      'a\nb'
    );
  });
});

describe('completionState', () => {
  const rendered = '# Generated by cdwr completion zsh\ncomplete a\n';

  it('is missing without a file', () => {
    expect(completionState(undefined, rendered)).toBe('missing');
  });

  it('is current when only the header differs', () => {
    expect(
      completionState(
        '# Generated by cdwr completion zsh v2\ncomplete a',
        rendered
      )
    ).toBe('current');
  });

  it('is stale when the body changed', () => {
    expect(
      completionState(
        '# Generated by cdwr completion zsh\ncomplete b\n',
        rendered
      )
    ).toBe('stale');
  });
});
