import { join } from 'node:path';

import type { Shell } from '../cli/completion';

/** Where `cdwr setup` writes the completion script for a shell */
export const completionFile = (
  shell: Shell,
  dirs: { cdwrHome: string; home: string }
): string =>
  shell === 'fish'
    ? join(dirs.home, '.config', 'fish', 'completions', 'cdwr.fish')
    : join(dirs.cdwrHome, `completion.${shell}`);

/** A script without its generated-by header and trailing whitespace */
export const normalise = (script: string): string =>
  script
    .split(/\r?\n/)
    .filter((line) => !line.startsWith('# Generated by'))
    .map((line) => line.trimEnd())
    .join('\n')
    .trimEnd();

export const completionState = (
  installed: string | undefined,
  rendered: string
): 'current' | 'stale' | 'missing' =>
  installed === undefined
    ? 'missing'
    : normalise(installed) === normalise(rendered)
      ? 'current'
      : 'stale';
