import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  offlineCacheFile,
  readOfflineCache,
  writeOfflineCache
} from './offline-cache';

describe('offlineCacheFile', () => {
  let ws: string;
  beforeEach(() => {
    ws = mkdtempSync(join(tmpdir(), 'infisical-ws-'));
    mkdirSync(join(ws, 'apps', 'cms'), { recursive: true });
    mkdirSync(join(ws, 'apps', 'web'), { recursive: true });
  });
  afterEach(() => rmSync(ws, { recursive: true, force: true }));

  it.each([
    ['/apps/cms', 'apps/cms/.env.offline'],
    ['/apps/cms/signature', 'apps/cms/.env.offline'],
    ['/apps/web', 'apps/web/.env.offline'],
    ['/apps/web/sub/folder', 'apps/web/.env.offline']
  ])('%s -> %s', (path, expected) => {
    expect(offlineCacheFile(ws, path)).toBe(join(ws, expected));
  });

  it.each(['/', '/tenants/moon', '/apps', '/apps/unknown', '/apps/../x'])(
    'rejects %s',
    (path) => {
      expect(() => offlineCacheFile(ws, path)).toThrow(
        `Infisical path must be under /apps/<app>: ${path}`
      );
    }
  );
});

describe('offline cache file', () => {
  let dir: string;
  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'infisical-cli-'));
  });
  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  const values = {
    PLAIN: 'value',
    QUOTES: 'say "hi" and \'bye\'',
    NEWLINE: 'line1\nline2\r\nline3',
    HASH: 'a # not a comment',
    EQUALS: 'a=b=c',
    BACKSLASH: 'C:\\temp\\x',
    EMPTY: '',
    UNICODE: 'åäö — ✓'
  };

  it('round-trips values', () => {
    const file = join(dir, '.env.offline');
    writeOfflineCache(file, {
      environment: 'development',
      paths: ['/apps/cms'],
      values
    });
    expect(readOfflineCache(file)).toEqual(values);
  });

  it('writes a header and sorted keys', () => {
    const file = join(dir, '.env.offline');
    writeOfflineCache(file, {
      environment: 'development',
      paths: ['/apps/cms', '/apps/cms/signature'],
      values: { B: '2', A: '1' }
    });
    const text = readFileSync(file, 'utf8');
    expect(text.split('\n').slice(0, 2)).toEqual([
      '# Generated by `cdwr infisical cache` — do not edit.',
      '# Infisical development, from /apps/cms, /apps/cms/signature'
    ]);
    expect(text.indexOf('A=')).toBeLessThan(text.indexOf('B='));
  });

  it('is private, also when the file pre-existed with wider access', () => {
    const fresh = join(dir, 'fresh');
    const existing = join(dir, 'existing');
    writeFileSync(existing, 'old', { mode: 0o644 });
    for (const file of [fresh, existing]) {
      writeOfflineCache(file, { environment: 'e', paths: ['/'], values });
      expect(statSync(file).mode & 0o777).toBe(0o600);
    }
  });

  it('leaves no temp file behind, on success or failure', () => {
    const file = join(dir, '.env.offline');
    writeOfflineCache(file, { environment: 'e', paths: ['/'], values });
    expect(readdirSync(dir)).toEqual(['.env.offline']);

    expect(() =>
      writeOfflineCache(join(dir, 'missing', '.env.offline'), {
        environment: 'e',
        paths: ['/'],
        values
      })
    ).toThrow();
    expect(readdirSync(dir)).toEqual(['.env.offline']);
  });

  it('points at the way to generate a missing cache', () => {
    expect(() => readOfflineCache(join(dir, 'web', '.env.offline'))).toThrow(
      'nx dx:secrets web'
    );
  });
});
