import {
  chmodSync,
  existsSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync
} from 'node:fs';
import { basename, dirname, join } from 'node:path';

import { parseDotenv } from './parse-dotenv';

/**
 * Generated, never hand-written, and kept apart from `.env` so refreshing it
 * cannot overwrite the public configuration living there.
 *
 * `/apps/web` and its sub-folders all cache to `apps/web/.env.offline`;
 * a path outside `/apps/<app>` has no cache and throws.
 */
export const offlineCacheFile = (
  workspaceRoot: string,
  path: string
): string => {
  const app = /^\/apps\/([^/.][^/]*)(?:\/|$)/.exec(path)?.[1];
  if (!app || !existsSync(join(workspaceRoot, 'apps', app))) {
    throw new Error(`Infisical path must be under /apps/<app>: ${path}`);
  }
  return join(workspaceRoot, 'apps', app, '.env.offline');
};

export const writeOfflineCache = (
  file: string,
  data: {
    environment: string;
    paths: string[];
    values: Record<string, string>;
  }
): void => {
  const lines = Object.keys(data.values)
    .sort()
    .map((key) => `${key}=${JSON.stringify(data.values[key])}`);

  // A private temp file renamed into place: never readable by others, never half-written
  const temp = `${file}.${process.pid}.tmp`;
  try {
    writeFileSync(
      temp,
      [
        '# Generated by `cdwr infisical cache` — do not edit.',
        `# Infisical ${data.environment}, from ${data.paths.join(', ')}`,
        '',
        ...lines,
        ''
      ].join('\n'),
      { mode: 0o600 }
    );
    // mode only applies when the file is created, so a leftover temp needs this too
    chmodSync(temp, 0o600);
    renameSync(temp, file);
  } catch (error) {
    rmSync(temp, { force: true });
    throw error;
  }
};

export const readOfflineCache = (file: string): Record<string, string> => {
  if (!existsSync(file)) {
    throw new Error(
      [
        `OFFLINE is set but ${file} does not exist.`,
        `  Generate it while you still have a session: nx dx:secrets ${basename(dirname(file))}`
      ].join('\n')
    );
  }
  return parseDotenv(readFileSync(file, 'utf8'));
};
