import { MigrateDownArgs, MigrateUpArgs, sql } from '@payloadcms/db-postgres';

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "payload"."enum_section_band" ADD VALUE IF NOT EXISTS 'gradient';`);
}

export async function down({
  db,
  payload,
  req
}: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "payload"."pages_blocks_about" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_about" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."pages_blocks_callout" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_callout" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."pages_blocks_card" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_card" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."pages_blocks_code" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_code" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."pages_blocks_form" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_form" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."pages_blocks_image" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_image" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."pages_blocks_social_media" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_social_media" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."pages_blocks_content" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_content" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."pages_blocks_feature_cards" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_feature_cards" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."pages_blocks_feature_section" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_feature_section" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."pages_blocks_file_area" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_file_area" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."pages_blocks_hero" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_hero" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."pages_blocks_pill_list" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_pill_list" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."pages_blocks_posts" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_posts" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."pages_blocks_showcase" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_showcase" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."pages_blocks_testimonial" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_testimonial" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."pages_blocks_theme_studio" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_theme_studio" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."pages_blocks_tours" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."pages_blocks_tours" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_about" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_about" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_callout" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_callout" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_card" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_card" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_code" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_code" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_form" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_form" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_image" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_image" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_social_media" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_social_media" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_content" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_content" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_feature_cards" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_feature_cards" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_feature_section" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_feature_section" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_file_area" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_file_area" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_hero" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_hero" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_pill_list" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_pill_list" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_posts" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_posts" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_showcase" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_showcase" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_testimonial" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_testimonial" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_theme_studio" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_theme_studio" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."_pages_v_blocks_tours" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."_pages_v_blocks_tours" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."reusable_content_blocks_card" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."reusable_content_blocks_card" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."reusable_content_blocks_code" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."reusable_content_blocks_code" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."reusable_content_blocks_form" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."reusable_content_blocks_form" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."reusable_content_blocks_image" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."reusable_content_blocks_image" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."reusable_content_blocks_social_media" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."reusable_content_blocks_social_media" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."reusable_content_blocks_content" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."reusable_content_blocks_content" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  ALTER TABLE "payload"."reusable_content_blocks_file_area" ALTER COLUMN "band" SET DATA TYPE text;
  ALTER TABLE "payload"."reusable_content_blocks_file_area" ALTER COLUMN "band" SET DEFAULT 'none'::text;
  -- The old type has no gradient: the closest band left is strong
  UPDATE "payload"."pages_blocks_about" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."pages_blocks_callout" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."pages_blocks_card" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."pages_blocks_code" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."pages_blocks_form" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."pages_blocks_image" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."pages_blocks_social_media" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."pages_blocks_content" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."pages_blocks_feature_cards" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."pages_blocks_feature_section" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."pages_blocks_file_area" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."pages_blocks_hero" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."pages_blocks_pill_list" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."pages_blocks_posts" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."pages_blocks_showcase" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."pages_blocks_testimonial" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."pages_blocks_theme_studio" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."pages_blocks_tours" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_about" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_callout" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_card" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_code" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_form" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_image" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_social_media" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_content" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_feature_cards" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_feature_section" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_file_area" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_hero" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_pill_list" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_posts" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_showcase" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_testimonial" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_theme_studio" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."_pages_v_blocks_tours" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."reusable_content_blocks_card" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."reusable_content_blocks_code" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."reusable_content_blocks_form" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."reusable_content_blocks_image" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."reusable_content_blocks_social_media" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."reusable_content_blocks_content" SET "band" = 'strong' WHERE "band" = 'gradient';
  UPDATE "payload"."reusable_content_blocks_file_area" SET "band" = 'strong' WHERE "band" = 'gradient';
  DROP TYPE "payload"."enum_section_band";
  CREATE TYPE "payload"."enum_section_band" AS ENUM('none', 'subtle', 'strong');
  ALTER TABLE "payload"."pages_blocks_about" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_about" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_callout" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_callout" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_card" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_card" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_code" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_code" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_form" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_form" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_image" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_image" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_social_media" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_social_media" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_content" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_content" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_feature_cards" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_feature_cards" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_feature_section" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_feature_section" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_file_area" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_file_area" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_hero" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_hero" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_pill_list" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_pill_list" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_posts" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_posts" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_showcase" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_showcase" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_testimonial" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_testimonial" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_theme_studio" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_theme_studio" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_tours" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."pages_blocks_tours" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_about" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_about" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_callout" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_callout" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_card" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_card" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_code" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_code" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_form" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_form" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_image" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_image" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_social_media" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_social_media" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_content" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_content" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_feature_cards" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_feature_cards" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_feature_section" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_feature_section" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_file_area" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_file_area" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_hero" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_hero" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_pill_list" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_pill_list" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_posts" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_posts" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_showcase" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_showcase" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_testimonial" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_testimonial" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_theme_studio" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_theme_studio" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_tours" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."_pages_v_blocks_tours" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."reusable_content_blocks_card" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."reusable_content_blocks_card" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."reusable_content_blocks_code" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."reusable_content_blocks_code" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."reusable_content_blocks_form" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."reusable_content_blocks_form" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."reusable_content_blocks_image" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."reusable_content_blocks_image" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."reusable_content_blocks_social_media" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."reusable_content_blocks_social_media" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."reusable_content_blocks_content" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."reusable_content_blocks_content" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";
  ALTER TABLE "payload"."reusable_content_blocks_file_area" ALTER COLUMN "band" SET DEFAULT 'none'::"payload"."enum_section_band";
  ALTER TABLE "payload"."reusable_content_blocks_file_area" ALTER COLUMN "band" SET DATA TYPE "payload"."enum_section_band" USING "band"::"payload"."enum_section_band";`);
}
