/* AUTO-GENERATED — do not edit manually. Run `pnpm nx sync` to update. */

/** One built-in theme's declarations, per colour scheme. */
export type BuiltInThemeTokens = {
  light: Record<string, string>;
  dark: Record<string, string>;
};

export const BUILT_IN_TOKENS: Record<string, BuiltInThemeTokens> = {
  frost: {
    light: {
      '--brand-50': 'var(--color-zinc-50)',
      '--brand-100': 'var(--color-zinc-100)',
      '--brand-200': 'var(--color-zinc-200)',
      '--brand-300': 'var(--color-zinc-300)',
      '--brand-400': 'var(--color-zinc-400)',
      '--brand-500': 'var(--color-zinc-500)',
      '--brand-600': 'var(--color-zinc-600)',
      '--brand-700': 'var(--color-zinc-700)',
      '--brand-800': 'var(--color-zinc-800)',
      '--brand-900': 'var(--color-zinc-900)',
      '--brand-950': 'var(--color-zinc-950)',
      '--radius': '0.625rem',
      '--radius-md': 'calc(var(--radius) - 0.125rem)',
      '--background': 'oklch(1 0 0)',
      '--foreground': 'oklch(0.145 0 0)',
      '--card': 'oklch(1 0 0)',
      '--card-foreground': 'oklch(0.145 0 0)',
      '--popover': 'oklch(1 0 0)',
      '--popover-foreground': 'oklch(0.145 0 0)',
      '--primary': 'oklch(0.205 0 0)',
      '--primary-foreground': 'oklch(0.985 0 0)',
      '--secondary': 'oklch(0.97 0 0)',
      '--secondary-foreground': 'oklch(0.205 0 0)',
      '--muted': 'oklch(0.97 0 0)',
      '--muted-foreground': 'oklch(0.536 0 0)',
      '--accent': 'oklch(0.97 0 0)',
      '--accent-foreground': 'oklch(0.205 0 0)',
      '--destructive': 'oklch(0.577 0.245 27.325)',
      '--destructive-foreground': 'oklch(1 0 0)',
      '--destructive-subtle': 'var(--color-red-700)',
      '--success-subtle': 'var(--color-green-700)',
      '--warning-subtle': 'var(--color-amber-700)',
      '--border': 'oklch(0.922 0 0)',
      '--input': 'oklch(0.922 0 0)',
      '--ring': 'oklch(0.556 0 0)',
      '--chart-1': 'oklch(0.87 0 0)',
      '--chart-2': 'oklch(0.556 0 0)',
      '--chart-3': 'oklch(0.439 0 0)',
      '--chart-4': 'oklch(0.371 0 0)',
      '--chart-5': 'oklch(0.269 0 0)',
      '--sidebar': 'oklch(0.985 0 0)',
      '--sidebar-foreground': 'oklch(0.145 0 0)',
      '--sidebar-primary': 'oklch(0.205 0 0)',
      '--sidebar-primary-foreground': 'oklch(0.985 0 0)',
      '--sidebar-accent': 'oklch(0.97 0 0)',
      '--sidebar-accent-foreground': 'oklch(0.205 0 0)',
      '--sidebar-border': 'oklch(0.922 0 0)',
      '--sidebar-ring': 'oklch(0.556 0 0)',
      '--core-action-btn-foreground': 'var(--muted-foreground)',
      '--core-action-btn-foreground-hover': 'var(--foreground)',
      '--core-action-btn-background': 'var(--background)',
      '--core-action-btn-track': 'var(--muted)',
      '--core-action-btn-border': 'var(--border)',
      '--core-action-btn-border-hover': 'var(--border)',
      '--core-action-btn-icon-fill': 'var(--muted)',
      '--core-action-btn-shadow': 'transparent',
      '--core-background-body': 'var(--background)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'var(--border)',
      '--core-sheet-edge': 'transparent',
      '--core-band-reach': 'calc(50% - 50vw)',
      '--core-band-subtle': 'var(--muted)',
      '--core-band-strong': 'var(--card)',
      '--core-font-body': 'Inter Variable, Inter, sans-serif',
      '--core-font-heading': 'Inter Variable, Inter, sans-serif',
      '--core-font-mono':
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
      '--core-header': 'var(--foreground)',
      '--core-headline': 'var(--foreground)',
      '--core-interactive': 'var(--brand-400)',
      '--core-link': 'var(--primary)',
      '--core-navbar': 'var(--background)',
      '--core-navbar-border': 'var(--border)',
      '--core-navbar-shadow': 'transparent',
      '--core-nav-link': 'var(--foreground)',
      '--core-nav-link-active': 'var(--primary)',
      '--core-nav-link-hover': 'var(--primary)',
      '--core-surface-invert': 'oklch(0.205 0 0)',
      '--core-text': 'var(--foreground)',
      '--body': 'var(--foreground)',
      '--bold': 'var(--foreground)',
      '--bullets': 'var(--primary)',
      '--captions': 'var(--muted-foreground)',
      '--code': 'var(--foreground)',
      '--code-bg': 'var(--muted)',
      '--counters': 'var(--primary)',
      '--headings': 'var(--foreground)',
      '--hr': 'var(--border)',
      '--links': 'var(--primary)',
      '--links-hover': 'var(--primary)',
      '--pre-bg': 'var(--secondary)',
      '--pre-border': 'var(--border)',
      '--pre-code': 'var(--foreground)',
      '--quote-borders': 'var(--border)',
      '--td-borders': 'var(--border)',
      '--th-borders': 'var(--border)',
      '--underline': 'var(--primary)',
      '--underline-hover': 'var(--primary)'
    },
    dark: {
      '--background': 'oklch(0.145 0 0)',
      '--foreground': 'oklch(0.985 0 0)',
      '--card': 'oklch(0.205 0 0)',
      '--card-foreground': 'oklch(0.985 0 0)',
      '--popover': 'oklch(0.205 0 0)',
      '--popover-foreground': 'oklch(0.985 0 0)',
      '--primary': 'oklch(0.922 0 0)',
      '--primary-foreground': 'oklch(0.205 0 0)',
      '--secondary': 'oklch(0.269 0 0)',
      '--secondary-foreground': 'oklch(0.985 0 0)',
      '--muted': 'oklch(0.269 0 0)',
      '--muted-foreground': 'oklch(0.708 0 0)',
      '--accent': 'oklch(0.269 0 0)',
      '--accent-foreground': 'oklch(0.985 0 0)',
      '--destructive': 'var(--color-red-700)',
      '--destructive-foreground': 'oklch(1 0 0)',
      '--destructive-subtle': 'var(--color-red-400)',
      '--success-subtle': 'var(--color-green-400)',
      '--warning-subtle': 'var(--color-amber-400)',
      '--border': 'oklch(1 0 0 / 10%)',
      '--input': 'oklch(1 0 0 / 15%)',
      '--ring': 'oklch(0.556 0 0)',
      '--chart-1': 'oklch(0.87 0 0)',
      '--chart-2': 'oklch(0.556 0 0)',
      '--chart-3': 'oklch(0.439 0 0)',
      '--chart-4': 'oklch(0.371 0 0)',
      '--chart-5': 'oklch(0.269 0 0)',
      '--sidebar': 'oklch(0.205 0 0)',
      '--sidebar-foreground': 'oklch(0.985 0 0)',
      '--sidebar-primary': 'oklch(0.488 0.243 264.376)',
      '--sidebar-primary-foreground': 'oklch(0.985 0 0)',
      '--sidebar-accent': 'oklch(0.269 0 0)',
      '--sidebar-accent-foreground': 'oklch(0.985 0 0)',
      '--sidebar-border': 'oklch(1 0 0 / 10%)',
      '--sidebar-ring': 'oklch(0.556 0 0)',
      '--core-surface-invert': 'var(--card)',
      '--core-band-subtle':
        'color-mix(in oklab, var(--card) 50%, var(--background))',
      '--core-band-strong': 'var(--card)'
    }
  },
  'payload-admin': {
    light: {
      '--brand-50': 'oklch(0.9666 0.011 243.652)',
      '--brand-100': 'oklch(0.9212 0.0252 236.841)',
      '--brand-200': 'oklch(0.8464 0.0465 242.325)',
      '--brand-300': 'oklch(0.7337 0.0676 244.661)',
      '--brand-400': 'oklch(0.6148 0.0764 239.668)',
      '--brand-500': 'oklch(0.5142 0.106 248.534)',
      '--brand-600': 'oklch(0.4235 0.1287 254.984)',
      '--brand-700': 'oklch(0.3687 0.1071 254.562)',
      '--brand-800': 'oklch(0.3177 0.0889 254.918)',
      '--brand-900': 'oklch(0.2599 0.0741 258.029)',
      '--brand-950': 'oklch(0.2104 0.0525 258.271)',
      '--radius': '0.625rem',
      '--radius-md': 'calc(var(--radius) - 0.125rem)',
      '--background': 'oklch(1 0 0)',
      '--foreground': 'oklch(0.141 0.005 285.823)',
      '--card': 'oklch(1 0 0)',
      '--card-foreground': 'oklch(0.141 0.005 285.823)',
      '--popover': 'oklch(1 0 0)',
      '--popover-foreground': 'oklch(0.141 0.005 285.823)',
      '--primary': 'oklch(0.21 0.006 285.885)',
      '--primary-foreground': 'oklch(0.985 0 0)',
      '--secondary': 'oklch(0.967 0.001 286.375)',
      '--secondary-foreground': 'oklch(0.21 0.006 285.885)',
      '--muted': 'oklch(0.967 0.001 286.375)',
      '--muted-foreground': 'oklch(0.536 0.016 285.938)',
      '--accent': 'oklch(0.967 0.001 286.375)',
      '--accent-foreground': 'oklch(0.21 0.006 285.885)',
      '--destructive': 'oklch(0.577 0.245 27.325)',
      '--destructive-foreground': 'oklch(1 0 0)',
      '--destructive-subtle': 'var(--color-red-700)',
      '--success-subtle': 'var(--color-green-700)',
      '--warning-subtle': 'var(--color-amber-700)',
      '--border': 'oklch(0.92 0.004 286.32)',
      '--input': 'oklch(0.92 0.004 286.32)',
      '--ring': 'oklch(0.552 0.016 285.938)',
      '--chart-1': 'oklch(0.646 0.222 41.116)',
      '--chart-2': 'oklch(0.6 0.118 184.704)',
      '--chart-3': 'oklch(0.398 0.07 227.392)',
      '--chart-4': 'oklch(0.828 0.189 84.429)',
      '--chart-5': 'oklch(0.769 0.188 70.08)',
      '--sidebar': 'oklch(0.985 0 0)',
      '--sidebar-foreground': 'oklch(0.141 0.005 285.823)',
      '--sidebar-primary': 'oklch(0.21 0.006 285.885)',
      '--sidebar-primary-foreground': 'oklch(0.985 0 0)',
      '--sidebar-accent': 'oklch(0.967 0.001 286.375)',
      '--sidebar-accent-foreground': 'oklch(0.21 0.006 285.885)',
      '--sidebar-border': 'oklch(0.92 0.004 286.32)',
      '--sidebar-ring': 'oklch(0.552 0.016 285.938)',
      '--link': 'var(--brand-600)',
      '--core-action-btn-foreground': 'var(--muted-foreground)',
      '--core-action-btn-foreground-hover': 'var(--foreground)',
      '--core-action-btn-background': 'var(--background)',
      '--core-action-btn-track': 'var(--muted)',
      '--core-action-btn-border': 'var(--border)',
      '--core-action-btn-border-hover': 'var(--border)',
      '--core-action-btn-icon-fill': 'var(--muted)',
      '--core-action-btn-shadow': 'transparent',
      '--core-background-body': 'var(--background)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'var(--border)',
      '--core-sheet-edge': 'transparent',
      '--core-band-reach': 'calc(50% - 50vw)',
      '--core-band-subtle': 'var(--muted)',
      '--core-band-strong': 'var(--card)',
      '--core-font-body': 'Inter Variable, Inter, sans-serif',
      '--core-font-heading': 'Inter Variable, Inter, sans-serif',
      '--core-font-mono':
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
      '--core-header': 'var(--foreground)',
      '--core-headline': 'var(--foreground)',
      '--core-interactive': 'var(--brand-400)',
      '--core-link': 'var(--link)',
      '--core-navbar': 'var(--background)',
      '--core-navbar-border': 'var(--border)',
      '--core-navbar-shadow': 'transparent',
      '--core-nav-link': 'var(--foreground)',
      '--core-nav-link-active': 'var(--primary)',
      '--core-nav-link-hover': 'var(--primary)',
      '--core-surface-invert': 'var(--primary)',
      '--core-text': 'var(--foreground)',
      '--body': 'var(--foreground)',
      '--bold': 'var(--foreground)',
      '--bullets': 'var(--primary)',
      '--captions': 'var(--muted-foreground)',
      '--code': 'var(--foreground)',
      '--code-bg': 'var(--muted)',
      '--counters': 'var(--primary)',
      '--headings': 'var(--foreground)',
      '--hr': 'var(--border)',
      '--links': 'var(--primary)',
      '--links-hover': 'var(--primary)',
      '--pre-bg': 'var(--secondary)',
      '--pre-border': 'var(--border)',
      '--pre-code': 'var(--foreground)',
      '--quote-borders': 'var(--border)',
      '--td-borders': 'var(--border)',
      '--th-borders': 'var(--border)',
      '--underline': 'var(--primary)',
      '--underline-hover': 'var(--primary)'
    },
    dark: {
      '--background': 'oklch(0.141 0.005 285.823)',
      '--foreground': 'oklch(0.985 0 0)',
      '--card': 'oklch(0.21 0.006 285.885)',
      '--card-foreground': 'oklch(0.985 0 0)',
      '--popover': 'oklch(0.21 0.006 285.885)',
      '--popover-foreground': 'oklch(0.985 0 0)',
      '--primary': 'oklch(0.92 0.004 286.32)',
      '--primary-foreground': 'oklch(0.21 0.006 285.885)',
      '--secondary': 'oklch(0.274 0.006 286.033)',
      '--secondary-foreground': 'oklch(0.985 0 0)',
      '--muted': 'oklch(0.274 0.006 286.033)',
      '--muted-foreground': 'oklch(0.705 0.015 286.067)',
      '--accent': 'oklch(0.274 0.006 286.033)',
      '--accent-foreground': 'oklch(0.985 0 0)',
      '--destructive': 'var(--color-red-700)',
      '--destructive-foreground': 'oklch(1 0 0)',
      '--destructive-subtle': 'var(--color-red-400)',
      '--success-subtle': 'var(--color-green-400)',
      '--warning-subtle': 'var(--color-amber-400)',
      '--border': 'oklch(1 0 0 / 10%)',
      '--input': 'oklch(1 0 0 / 15%)',
      '--ring': 'oklch(0.552 0.016 285.938)',
      '--chart-1': 'oklch(0.488 0.243 264.376)',
      '--chart-2': 'oklch(0.696 0.17 162.48)',
      '--chart-3': 'oklch(0.769 0.188 70.08)',
      '--chart-4': 'oklch(0.627 0.265 303.9)',
      '--chart-5': 'oklch(0.645 0.246 16.439)',
      '--sidebar': 'oklch(0.21 0.006 285.885)',
      '--sidebar-foreground': 'oklch(0.985 0 0)',
      '--sidebar-primary': 'oklch(0.488 0.243 264.376)',
      '--sidebar-primary-foreground': 'oklch(0.985 0 0)',
      '--sidebar-accent': 'oklch(0.274 0.006 286.033)',
      '--sidebar-accent-foreground': 'oklch(0.985 0 0)',
      '--sidebar-border': 'oklch(1 0 0 / 10%)',
      '--sidebar-ring': 'oklch(0.552 0.016 285.938)',
      '--link': 'var(--brand-300)',
      '--core-link': 'var(--link)',
      '--core-surface-invert': 'var(--card)',
      '--core-band-subtle':
        'color-mix(in oklab, var(--card) 50%, var(--background))',
      '--core-band-strong': 'var(--card)'
    }
  },
  spotlight: {
    light: {
      '--brand-50': 'var(--color-teal-50)',
      '--brand-100': 'var(--color-teal-100)',
      '--brand-200': 'var(--color-teal-200)',
      '--brand-300': 'var(--color-teal-300)',
      '--brand-400': 'var(--color-teal-400)',
      '--brand-500': 'var(--color-teal-500)',
      '--brand-600': 'var(--color-teal-600)',
      '--brand-700': 'var(--color-teal-700)',
      '--brand-800': 'var(--color-teal-800)',
      '--brand-900': 'var(--color-teal-900)',
      '--brand-950': 'var(--color-teal-950)',
      '--radius': '0.5rem',
      '--radius-md': 'calc(var(--radius) - 0.125rem)',
      '--background': 'var(--color-white)',
      '--foreground': 'var(--core-text)',
      '--card': 'var(--color-zinc-50)',
      '--card-foreground': 'var(--color-zinc-600)',
      '--popover': 'var(--color-zinc-50)',
      '--popover-foreground': 'var(--color-zinc-900)',
      '--secondary': 'var(--color-zinc-100)',
      '--secondary-foreground': 'var(--color-zinc-900)',
      '--muted': 'var(--color-zinc-100)',
      '--muted-foreground': 'var(--color-zinc-600)',
      '--accent': 'var(--color-zinc-100)',
      '--accent-foreground': 'var(--color-zinc-900)',
      '--destructive': 'var(--color-red-600)',
      '--destructive-foreground': 'var(--color-white)',
      '--border': 'var(--color-zinc-100)',
      '--input': 'var(--color-zinc-300)',
      '--sidebar': 'var(--color-zinc-50)',
      '--sidebar-foreground': 'var(--color-zinc-950)',
      '--sidebar-accent': 'var(--color-zinc-100)',
      '--sidebar-accent-foreground': 'var(--color-zinc-900)',
      '--sidebar-border': 'var(--color-zinc-200)',
      '--primary': 'var(--color-zinc-900)',
      '--primary-foreground': 'var(--color-zinc-50)',
      '--ring': 'var(--color-zinc-900)',
      '--sidebar-primary': 'var(--color-zinc-900)',
      '--sidebar-primary-foreground': 'var(--color-zinc-50)',
      '--sidebar-ring': 'var(--color-zinc-400)',
      '--chart-1': 'var(--color-orange-600)',
      '--chart-2': 'var(--color-teal-600)',
      '--chart-3': 'var(--color-cyan-900)',
      '--chart-4': 'var(--color-amber-400)',
      '--chart-5': 'var(--color-amber-500)',
      '--destructive-subtle': 'var(--color-red-700)',
      '--success-subtle': 'var(--color-green-700)',
      '--warning-subtle': 'var(--color-amber-700)',
      '--core-font-mono':
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
      '--core-action-btn-foreground': 'var(--muted-foreground)',
      '--core-action-btn-foreground-hover': 'var(--color-teal-700)',
      '--core-action-btn-background': 'oklch(1 0 0 / 90%)',
      '--core-action-btn-track': 'var(--color-zinc-100)',
      '--core-action-btn-border': 'oklch(0.21 0.006 285.885 / 5%)',
      '--core-action-btn-border-hover': 'oklch(0.21 0.006 285.885 / 10%)',
      '--core-action-btn-icon-fill': 'var(--muted)',
      '--core-action-btn-shadow': 'oklch(0.274 0.006 286.033 / 5%)',
      '--core-header': 'var(--color-zinc-900)',
      '--core-headline': 'var(--color-zinc-800)',
      '--core-navbar': 'oklch(1 0 0 / 90%)',
      '--core-navbar-border': 'oklch(0.21 0.006 285.885 / 5%)',
      '--core-navbar-shadow': 'oklch(0.274 0.006 286.033 / 5%)',
      '--core-nav-link': 'var(--color-zinc-800)',
      '--core-nav-link-active': 'var(--color-teal-700)',
      '--core-nav-link-hover': 'var(--color-teal-700)',
      '--core-text': 'var(--color-zinc-600)',
      '--body': 'var(--core-text)',
      '--bold': 'var(--primary)',
      '--bullets': 'var(--primary)',
      '--captions': 'var(--color-zinc-500)',
      '--code': 'var(--color-zinc-700)',
      '--code-bg': 'oklch(0.871 0.006 286.286 / 20%)',
      '--counters': 'var(--primary)',
      '--headings': 'var(--core-header)',
      '--hr': 'var(--color-zinc-300)',
      '--links': 'var(--brand-600)',
      '--links-hover': 'var(--brand-600)',
      '--pre-bg': 'var(--color-zinc-900)',
      '--pre-border': 'transparent',
      '--pre-code': 'var(--secondary)',
      '--quote-borders': 'var(--color-zinc-200)',
      '--td-borders': 'var(--secondary)',
      '--th-borders': 'var(--color-zinc-200)',
      '--underline': 'oklch(0.704 0.14 182.503 / 20%)',
      '--underline-hover': 'var(--brand-500)',
      '--core-background-body': 'var(--color-zinc-50)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'var(--color-zinc-100)',
      '--core-sheet-edge': 'var(--core-content-border)',
      '--core-band-reach': '0px',
      '--core-band-subtle': 'var(--muted)',
      '--core-band-strong': 'var(--card)',
      '--core-font-body': 'Inter Variable, Inter, sans-serif',
      '--core-font-heading': 'Inter Variable, Inter, sans-serif',
      '--core-interactive': 'var(--brand-400)',
      '--core-link': 'var(--brand-700)',
      '--core-surface-invert': 'var(--color-zinc-900)'
    },
    dark: {
      '--background': 'var(--core-background-content)',
      '--foreground': 'var(--core-text)',
      '--card': 'oklch(0.274 0.006 286.033 / 50%)',
      '--card-foreground': 'var(--color-zinc-400)',
      '--popover': 'var(--secondary)',
      '--popover-foreground': 'var(--secondary-foreground)',
      '--secondary': 'var(--color-zinc-800)',
      '--secondary-foreground': 'var(--color-zinc-100)',
      '--muted': 'var(--color-zinc-800)',
      '--muted-foreground': 'var(--color-zinc-400)',
      '--accent': 'var(--color-zinc-800)',
      '--accent-foreground': 'var(--color-zinc-100)',
      '--destructive': 'var(--color-red-600)',
      '--destructive-foreground': 'var(--color-white)',
      '--border': 'oklch(0.37 0.013 285.805 / 40%)',
      '--input': 'oklch(0.37 0.013 285.805 / 40%)',
      '--sidebar': 'var(--color-zinc-900)',
      '--sidebar-foreground': 'var(--color-zinc-50)',
      '--sidebar-accent': 'var(--color-zinc-800)',
      '--sidebar-accent-foreground': 'var(--color-zinc-50)',
      '--sidebar-border': 'oklch(1 0 0 / 10%)',
      '--primary': 'var(--color-zinc-100)',
      '--primary-foreground': 'var(--color-zinc-900)',
      '--ring': 'var(--primary)',
      '--sidebar-primary': 'oklch(0.488 0.243 264.376)',
      '--sidebar-primary-foreground': 'oklch(0.985 0 0)',
      '--sidebar-ring': 'var(--color-zinc-500)',
      '--chart-1': 'var(--color-blue-700)',
      '--chart-2': 'var(--color-emerald-500)',
      '--chart-3': 'var(--color-amber-500)',
      '--chart-4': 'var(--color-purple-500)',
      '--chart-5': 'var(--color-rose-500)',
      '--destructive-subtle': 'var(--color-red-400)',
      '--success-subtle': 'var(--color-green-400)',
      '--warning-subtle': 'var(--color-amber-400)',
      '--core-background-body': 'var(--color-black)',
      '--core-background-content': 'var(--color-zinc-900)',
      '--core-content-border': 'oklch(0.871 0.006 286.286 / 20%)',
      '--core-link': 'var(--brand-400)',
      '--core-surface-invert': 'var(--color-zinc-700)',
      '--core-action-btn-foreground-hover': 'var(--color-teal-400)',
      '--core-action-btn-background': 'oklch(0.274 0.006 286.033 / 90%)',
      '--core-action-btn-track': 'var(--color-zinc-900)',
      '--core-action-btn-border': 'oklch(1 0 0 / 10%)',
      '--core-action-btn-border-hover': 'oklch(1 0 0 / 20%)',
      '--core-action-btn-icon-fill': 'var(--color-zinc-700)',
      '--core-action-btn-shadow': 'oklch(0.274 0.006 286.033 / 5%)',
      '--core-header': 'var(--color-zinc-200)',
      '--core-headline': 'var(--color-zinc-100)',
      '--core-navbar': 'oklch(0.274 0.006 286.033 / 90%)',
      '--core-navbar-border': 'oklch(1 0 0 / 10%)',
      '--core-navbar-shadow': 'oklch(0.274 0.006 286.033 / 5%)',
      '--core-nav-link': 'var(--color-zinc-200)',
      '--core-nav-link-active': 'var(--color-teal-400)',
      '--core-nav-link-hover': 'var(--color-teal-400)',
      '--core-text': 'var(--color-zinc-400)',
      '--body': 'var(--core-text)',
      '--bold': 'var(--color-zinc-200)',
      '--code': 'var(--color-zinc-300)',
      '--code-bg': 'oklch(0.92 0.004 286.32 / 5%)',
      '--headings': 'var(--core-header)',
      '--hr': 'oklch(0.442 0.017 285.786 / 40%)',
      '--pre-bg': 'rgb(0 0 0 / 0.4)',
      '--pre-border': 'oklch(0.92 0.004 286.32 / 10%)',
      '--pre-code': 'var(--color-zinc-100)',
      '--quote-borders': 'var(--color-zinc-500)',
      '--td-borders': 'var(--color-zinc-800)',
      '--th-borders': 'var(--color-zinc-700)',
      '--underline': 'oklch(0.777 0.152 181.912 / 30%)',
      '--bullets': 'var(--color-zinc-200)',
      '--captions': 'var(--color-zinc-400)',
      '--counters': 'var(--color-zinc-200)',
      '--links': 'var(--color-teal-400)',
      '--links-hover': 'var(--color-teal-400)',
      '--underline-hover': 'var(--color-teal-400)',
      '--core-band-subtle':
        'color-mix(in oklab, var(--card) 50%, var(--background))',
      '--core-band-strong': 'var(--card)'
    }
  },
  codeware: {
    light: {
      '--steel-blue': '#588bae',
      '--yale-blue': '#0e4d92',
      '--space-cadet': '#1d2951',
      '--light-gray': '#d0d2d3',
      '--eerie-black': '#242526',
      '--darker-black': '#111111',
      '--brand-50': 'oklch(0.9666 0.011 243.652)',
      '--brand-100': 'oklch(0.9212 0.0252 236.841)',
      '--brand-200': 'oklch(0.8464 0.0465 242.325)',
      '--brand-300': 'oklch(0.7337 0.0676 244.661)',
      '--brand-400': 'oklch(0.6148 0.0764 239.668)',
      '--brand-500': 'oklch(0.5142 0.106 248.534)',
      '--brand-600': 'oklch(0.4235 0.1287 254.984)',
      '--brand-700': 'oklch(0.3687 0.1071 254.562)',
      '--brand-800': 'oklch(0.3177 0.0889 254.918)',
      '--brand-900': 'oklch(0.2599 0.0741 258.029)',
      '--brand-950': 'oklch(0.2104 0.0525 258.271)',
      '--radius': '0.625rem',
      '--radius-md': 'calc(var(--radius) - 0.125rem)',
      '--background': 'oklch(1 0 0)',
      '--foreground': 'oklch(0.141 0.005 285.823)',
      '--card': 'oklch(1 0 0)',
      '--card-foreground': 'oklch(0.141 0.005 285.823)',
      '--popover': 'oklch(1 0 0)',
      '--popover-foreground': 'oklch(0.141 0.005 285.823)',
      '--primary': 'oklch(0.21 0.006 285.885)',
      '--primary-foreground': 'oklch(0.985 0 0)',
      '--secondary': 'oklch(0.967 0.001 286.375)',
      '--secondary-foreground': 'oklch(0.21 0.006 285.885)',
      '--muted': 'oklch(0.967 0.001 286.375)',
      '--muted-foreground': 'oklch(0.536 0.016 285.938)',
      '--accent': 'oklch(0.967 0.001 286.375)',
      '--accent-foreground': 'oklch(0.21 0.006 285.885)',
      '--destructive': 'oklch(0.577 0.245 27.325)',
      '--destructive-foreground': 'oklch(1 0 0)',
      '--destructive-subtle': 'var(--color-red-700)',
      '--success-subtle': 'var(--color-green-700)',
      '--warning-subtle': 'var(--color-amber-700)',
      '--border': 'oklch(0.92 0.004 286.32)',
      '--input': 'oklch(0.92 0.004 286.32)',
      '--ring': 'oklch(0.552 0.016 285.938)',
      '--chart-1': 'oklch(0.646 0.222 41.116)',
      '--chart-2': 'oklch(0.6 0.118 184.704)',
      '--chart-3': 'oklch(0.398 0.07 227.392)',
      '--chart-4': 'oklch(0.828 0.189 84.429)',
      '--chart-5': 'oklch(0.769 0.188 70.08)',
      '--sidebar': 'oklch(0.985 0 0)',
      '--sidebar-foreground': 'oklch(0.141 0.005 285.823)',
      '--sidebar-primary': 'oklch(0.21 0.006 285.885)',
      '--sidebar-primary-foreground': 'oklch(0.985 0 0)',
      '--sidebar-accent': 'oklch(0.967 0.001 286.375)',
      '--sidebar-accent-foreground': 'oklch(0.21 0.006 285.885)',
      '--sidebar-border': 'oklch(0.92 0.004 286.32)',
      '--sidebar-ring': 'oklch(0.552 0.016 285.938)',
      '--core-action-btn-foreground': 'var(--muted-foreground)',
      '--core-action-btn-foreground-hover': 'var(--foreground)',
      '--core-action-btn-background': 'var(--background)',
      '--core-action-btn-track': 'var(--muted)',
      '--core-action-btn-border': 'var(--border)',
      '--core-action-btn-border-hover': 'var(--border)',
      '--core-action-btn-icon-fill': 'var(--muted)',
      '--core-action-btn-shadow': 'transparent',
      '--core-background-body': 'var(--background)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'var(--border)',
      '--core-sheet-edge': 'transparent',
      '--core-band-reach': 'calc(50% - 50vw)',
      '--core-band-subtle': 'var(--muted)',
      '--core-band-strong': 'var(--card)',
      '--core-font-body': 'Inter Variable, Inter, sans-serif',
      '--core-font-heading': 'Inter Variable, Inter, sans-serif',
      '--core-font-mono':
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
      '--core-header': 'var(--foreground)',
      '--core-headline': 'var(--foreground)',
      '--core-interactive': 'var(--brand-400)',
      '--core-link': 'var(--brand-600)',
      '--core-surface-invert': 'var(--eerie-black)',
      '--core-navbar': 'var(--background)',
      '--core-navbar-border': 'var(--border)',
      '--core-navbar-shadow': 'transparent',
      '--core-nav-link': 'var(--foreground)',
      '--core-nav-link-active': 'var(--primary)',
      '--core-nav-link-hover': 'var(--primary)',
      '--core-text': 'var(--foreground)',
      '--body': 'var(--foreground)',
      '--bold': 'var(--foreground)',
      '--bullets': 'var(--primary)',
      '--captions': 'var(--muted-foreground)',
      '--code': 'var(--foreground)',
      '--code-bg': 'var(--muted)',
      '--counters': 'var(--primary)',
      '--headings': 'var(--foreground)',
      '--hr': 'var(--border)',
      '--links': 'var(--primary)',
      '--links-hover': 'var(--primary)',
      '--pre-bg': 'var(--secondary)',
      '--pre-border': 'var(--border)',
      '--pre-code': 'var(--foreground)',
      '--quote-borders': 'var(--border)',
      '--td-borders': 'var(--border)',
      '--th-borders': 'var(--border)',
      '--underline': 'var(--primary)',
      '--underline-hover': 'var(--primary)'
    },
    dark: {
      '--background': 'oklch(0.141 0.005 285.823)',
      '--foreground': 'oklch(0.985 0 0)',
      '--card': 'oklch(0.21 0.006 285.885)',
      '--card-foreground': 'oklch(0.985 0 0)',
      '--popover': 'oklch(0.21 0.006 285.885)',
      '--popover-foreground': 'oklch(0.985 0 0)',
      '--primary': 'oklch(0.92 0.004 286.32)',
      '--primary-foreground': 'oklch(0.21 0.006 285.885)',
      '--secondary': 'oklch(0.274 0.006 286.033)',
      '--secondary-foreground': 'oklch(0.985 0 0)',
      '--muted': 'oklch(0.274 0.006 286.033)',
      '--muted-foreground': 'oklch(0.705 0.015 286.067)',
      '--accent': 'oklch(0.274 0.006 286.033)',
      '--accent-foreground': 'oklch(0.985 0 0)',
      '--destructive': 'var(--color-red-700)',
      '--destructive-foreground': 'oklch(1 0 0)',
      '--destructive-subtle': 'var(--color-red-400)',
      '--success-subtle': 'var(--color-green-400)',
      '--warning-subtle': 'var(--color-amber-400)',
      '--border': 'oklch(1 0 0 / 10%)',
      '--input': 'oklch(1 0 0 / 15%)',
      '--ring': 'oklch(0.552 0.016 285.938)',
      '--chart-1': 'oklch(0.488 0.243 264.376)',
      '--chart-2': 'oklch(0.696 0.17 162.48)',
      '--chart-3': 'oklch(0.769 0.188 70.08)',
      '--chart-4': 'oklch(0.627 0.265 303.9)',
      '--chart-5': 'oklch(0.645 0.246 16.439)',
      '--sidebar': 'oklch(0.21 0.006 285.885)',
      '--sidebar-foreground': 'oklch(0.985 0 0)',
      '--sidebar-primary': 'oklch(0.488 0.243 264.376)',
      '--sidebar-primary-foreground': 'oklch(0.985 0 0)',
      '--sidebar-accent': 'oklch(0.274 0.006 286.033)',
      '--sidebar-accent-foreground': 'oklch(0.985 0 0)',
      '--sidebar-border': 'oklch(1 0 0 / 10%)',
      '--sidebar-ring': 'oklch(0.552 0.016 285.938)',
      '--core-link': 'var(--brand-400)',
      '--core-surface-invert': 'var(--card)',
      '--core-band-subtle':
        'color-mix(in oklab, var(--card) 50%, var(--background))',
      '--core-band-strong': 'var(--card)'
    }
  },
  archipelago: {
    light: {
      '--brand-50': 'var(--color-cyan-50)',
      '--brand-100': 'var(--color-cyan-100)',
      '--brand-200': 'var(--color-cyan-200)',
      '--brand-300': 'var(--color-cyan-300)',
      '--brand-400': 'var(--color-cyan-400)',
      '--brand-500': 'var(--color-cyan-500)',
      '--brand-600': 'var(--color-cyan-600)',
      '--brand-700': 'var(--color-cyan-700)',
      '--brand-800': 'var(--color-cyan-800)',
      '--brand-900': 'var(--color-cyan-900)',
      '--brand-950': 'var(--color-cyan-950)',
      '--radius': '0.5rem',
      '--radius-md': 'calc(var(--radius) - 0.125rem)',
      '--background': 'var(--color-white)',
      '--foreground': 'oklch(0.148 0.004 228.8)',
      '--card': 'var(--color-white)',
      '--card-foreground': 'oklch(0.148 0.004 228.8)',
      '--popover': 'var(--color-white)',
      '--popover-foreground': 'oklch(0.148 0.004 228.8)',
      '--secondary': 'oklch(0.963 0.002 197.1)',
      '--secondary-foreground': 'oklch(0.218 0.008 223.9)',
      '--muted': 'oklch(0.963 0.002 197.1)',
      '--muted-foreground': 'oklch(0.45 0.017 213.2)',
      '--accent': 'oklch(0.963 0.002 197.1)',
      '--accent-foreground': 'oklch(0.218 0.008 223.9)',
      '--destructive': 'var(--color-red-600)',
      '--destructive-foreground': 'var(--color-white)',
      '--border': 'oklch(0.925 0.005 214.3)',
      '--input': 'oklch(0.925 0.005 214.3)',
      '--sidebar': 'oklch(0.987 0.002 197.1)',
      '--sidebar-foreground': 'oklch(0.148 0.004 228.8)',
      '--sidebar-accent': 'oklch(0.963 0.002 197.1)',
      '--sidebar-accent-foreground': 'oklch(0.218 0.008 223.9)',
      '--sidebar-border': 'oklch(0.925 0.005 214.3)',
      '--primary': 'var(--color-cyan-700)',
      '--primary-foreground': 'var(--color-white)',
      '--ring': 'var(--color-cyan-700)',
      '--sidebar-primary': 'var(--color-cyan-700)',
      '--sidebar-primary-foreground': 'var(--color-white)',
      '--sidebar-ring': 'var(--color-cyan-700)',
      '--chart-1': 'var(--color-cyan-600)',
      '--chart-2': 'var(--color-violet-600)',
      '--chart-3': 'var(--color-pink-600)',
      '--chart-4': 'var(--color-yellow-600)',
      '--chart-5': 'var(--color-green-600)',
      '--destructive-subtle': 'var(--color-red-700)',
      '--success-subtle': 'var(--color-green-700)',
      '--warning-subtle': 'var(--color-amber-700)',
      '--core-font-mono':
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
      '--core-action-btn-foreground': 'var(--muted-foreground)',
      '--core-action-btn-foreground-hover': 'var(--foreground)',
      '--core-action-btn-background': 'var(--background)',
      '--core-action-btn-track': 'var(--muted)',
      '--core-action-btn-border': 'var(--border)',
      '--core-action-btn-border-hover': 'var(--border)',
      '--core-action-btn-icon-fill': 'var(--muted)',
      '--core-action-btn-shadow': 'transparent',
      '--core-header': 'var(--foreground)',
      '--core-headline': 'var(--foreground)',
      '--core-interactive': 'var(--brand-400)',
      '--core-navbar': 'var(--background)',
      '--core-navbar-border': 'var(--border)',
      '--core-navbar-shadow': 'transparent',
      '--core-nav-link': 'var(--foreground)',
      '--core-nav-link-active': 'var(--primary)',
      '--core-nav-link-hover': 'var(--primary)',
      '--core-text': 'var(--foreground)',
      '--body': 'var(--foreground)',
      '--bold': 'var(--foreground)',
      '--bullets': 'var(--primary)',
      '--captions': 'var(--muted-foreground)',
      '--code': 'var(--foreground)',
      '--code-bg': 'var(--muted)',
      '--counters': 'var(--primary)',
      '--headings': 'var(--foreground)',
      '--hr': 'var(--border)',
      '--links': 'var(--core-link)',
      '--links-hover': 'var(--core-link)',
      '--pre-bg': 'var(--secondary)',
      '--pre-border': 'var(--border)',
      '--pre-code': 'var(--foreground)',
      '--quote-borders': 'var(--border)',
      '--td-borders': 'var(--border)',
      '--th-borders': 'var(--border)',
      '--underline': 'var(--core-link)',
      '--underline-hover': 'var(--core-link)',
      '--core-background-body': 'oklch(0.987 0.002 197.1)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'oklch(0.963 0.002 197.1)',
      '--core-sheet-edge': 'var(--core-content-border)',
      '--core-band-reach': '0px',
      '--core-band-subtle': 'var(--muted)',
      '--core-band-strong': 'var(--card)',
      '--core-font-body': 'Inter Variable, Inter, sans-serif',
      '--core-font-heading': 'Inter Variable, Inter, sans-serif',
      '--core-link': 'var(--brand-700)',
      '--core-surface-invert': 'oklch(0.218 0.008 223.9)'
    },
    dark: {
      '--background': 'oklch(0.148 0.004 228.8)',
      '--foreground': 'oklch(0.987 0.002 197.1)',
      '--card': 'oklch(0.218 0.008 223.9)',
      '--card-foreground': 'oklch(0.987 0.002 197.1)',
      '--popover': 'oklch(0.218 0.008 223.9)',
      '--popover-foreground': 'oklch(0.987 0.002 197.1)',
      '--secondary': 'oklch(0.275 0.011 216.9)',
      '--secondary-foreground': 'oklch(0.987 0.002 197.1)',
      '--muted': 'oklch(0.275 0.011 216.9)',
      '--muted-foreground': 'oklch(0.723 0.014 214.4)',
      '--accent': 'oklch(0.275 0.011 216.9)',
      '--accent-foreground': 'oklch(0.987 0.002 197.1)',
      '--destructive': 'var(--color-red-700)',
      '--destructive-foreground': 'var(--color-white)',
      '--border': 'oklch(1 0 0 / 10%)',
      '--input': 'oklch(1 0 0 / 15%)',
      '--sidebar': 'oklch(0.218 0.008 223.9)',
      '--sidebar-foreground': 'oklch(0.987 0.002 197.1)',
      '--sidebar-accent': 'oklch(0.275 0.011 216.9)',
      '--sidebar-accent-foreground': 'oklch(0.987 0.002 197.1)',
      '--sidebar-border': 'oklch(1 0 0 / 10%)',
      '--primary': 'var(--color-cyan-400)',
      '--primary-foreground': 'var(--color-cyan-950)',
      '--ring': 'var(--color-cyan-400)',
      '--sidebar-primary': 'var(--color-cyan-400)',
      '--sidebar-primary-foreground': 'var(--color-cyan-950)',
      '--sidebar-ring': 'var(--color-cyan-400)',
      '--chart-1': 'var(--color-cyan-400)',
      '--chart-2': 'var(--color-violet-400)',
      '--chart-3': 'var(--color-pink-400)',
      '--chart-4': 'var(--color-yellow-400)',
      '--chart-5': 'var(--color-green-400)',
      '--destructive-subtle': 'var(--color-red-400)',
      '--success-subtle': 'var(--color-green-400)',
      '--warning-subtle': 'var(--color-amber-400)',
      '--core-background-body': 'var(--background)',
      '--core-background-content': 'var(--card)',
      '--core-content-border': 'var(--border)',
      '--core-band-subtle':
        'color-mix(in oklab, var(--card) 50%, var(--background))',
      '--core-band-strong': 'var(--background)',
      '--core-link': 'var(--brand-400)',
      '--core-surface-invert': 'var(--card)'
    }
  },
  midsummer: {
    light: {
      '--brand-50': 'var(--color-amber-50)',
      '--brand-100': 'var(--color-amber-100)',
      '--brand-200': 'var(--color-amber-200)',
      '--brand-300': 'var(--color-amber-300)',
      '--brand-400': 'var(--color-amber-400)',
      '--brand-500': 'var(--color-amber-500)',
      '--brand-600': 'var(--color-amber-600)',
      '--brand-700': 'var(--color-amber-700)',
      '--brand-800': 'var(--color-amber-800)',
      '--brand-900': 'var(--color-amber-900)',
      '--brand-950': 'var(--color-amber-950)',
      '--radius': '1rem',
      '--radius-md': 'calc(var(--radius) - 0.125rem)',
      '--background': 'var(--color-white)',
      '--foreground': 'oklch(0.153 0.006 107.1)',
      '--card': 'var(--color-white)',
      '--card-foreground': 'oklch(0.153 0.006 107.1)',
      '--popover': 'var(--color-white)',
      '--popover-foreground': 'oklch(0.153 0.006 107.1)',
      '--secondary': 'oklch(0.966 0.005 106.5)',
      '--secondary-foreground': 'oklch(0.228 0.013 107.4)',
      '--muted': 'oklch(0.966 0.005 106.5)',
      '--muted-foreground': 'oklch(0.466 0.025 107.3)',
      '--accent': 'oklch(0.966 0.005 106.5)',
      '--accent-foreground': 'oklch(0.228 0.013 107.4)',
      '--destructive': 'var(--color-red-600)',
      '--destructive-foreground': 'var(--color-white)',
      '--border': 'oklch(0.93 0.007 106.5)',
      '--input': 'oklch(0.93 0.007 106.5)',
      '--sidebar': 'oklch(0.988 0.003 106.5)',
      '--sidebar-foreground': 'oklch(0.153 0.006 107.1)',
      '--sidebar-accent': 'oklch(0.966 0.005 106.5)',
      '--sidebar-accent-foreground': 'oklch(0.228 0.013 107.4)',
      '--sidebar-border': 'oklch(0.93 0.007 106.5)',
      '--primary': 'var(--color-amber-700)',
      '--primary-foreground': 'var(--color-white)',
      '--ring': 'var(--color-amber-700)',
      '--sidebar-primary': 'var(--color-amber-700)',
      '--sidebar-primary-foreground': 'var(--color-white)',
      '--sidebar-ring': 'var(--color-amber-700)',
      '--chart-1': 'var(--color-amber-600)',
      '--chart-2': 'var(--color-lime-600)',
      '--chart-3': 'var(--color-teal-600)',
      '--chart-4': 'var(--color-indigo-600)',
      '--chart-5': 'var(--color-pink-600)',
      '--destructive-subtle': 'var(--color-red-700)',
      '--success-subtle': 'var(--color-green-700)',
      '--warning-subtle': 'var(--color-amber-700)',
      '--core-font-mono':
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
      '--core-action-btn-foreground': 'var(--muted-foreground)',
      '--core-action-btn-foreground-hover': 'var(--foreground)',
      '--core-action-btn-background': 'var(--background)',
      '--core-action-btn-track': 'var(--muted)',
      '--core-action-btn-border': 'var(--border)',
      '--core-action-btn-border-hover': 'var(--border)',
      '--core-action-btn-icon-fill': 'var(--muted)',
      '--core-action-btn-shadow': 'transparent',
      '--core-header': 'var(--foreground)',
      '--core-headline': 'var(--foreground)',
      '--core-interactive': 'var(--brand-400)',
      '--core-navbar': 'var(--background)',
      '--core-navbar-border': 'var(--border)',
      '--core-navbar-shadow': 'transparent',
      '--core-nav-link': 'var(--foreground)',
      '--core-nav-link-active': 'var(--primary)',
      '--core-nav-link-hover': 'var(--primary)',
      '--core-text': 'var(--foreground)',
      '--body': 'var(--foreground)',
      '--bold': 'var(--foreground)',
      '--bullets': 'var(--primary)',
      '--captions': 'var(--muted-foreground)',
      '--code': 'var(--foreground)',
      '--code-bg': 'var(--muted)',
      '--counters': 'var(--primary)',
      '--headings': 'var(--foreground)',
      '--hr': 'var(--border)',
      '--links': 'var(--core-link)',
      '--links-hover': 'var(--core-link)',
      '--pre-bg': 'var(--secondary)',
      '--pre-border': 'var(--border)',
      '--pre-code': 'var(--foreground)',
      '--quote-borders': 'var(--border)',
      '--td-borders': 'var(--border)',
      '--th-borders': 'var(--border)',
      '--underline': 'var(--core-link)',
      '--underline-hover': 'var(--core-link)',
      '--core-background-body': 'var(--background)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'var(--border)',
      '--core-sheet-edge': 'transparent',
      '--core-band-reach': 'calc(50% - 50vw)',
      '--core-band-subtle': 'var(--muted)',
      '--core-band-strong': 'var(--card)',
      '--core-font-body': 'Inter Variable, Inter, sans-serif',
      '--core-font-heading': 'Inter Variable, Inter, sans-serif',
      '--core-link': 'var(--brand-800)',
      '--core-surface-invert': 'oklch(0.228 0.013 107.4)'
    },
    dark: {
      '--background': 'oklch(0.153 0.006 107.1)',
      '--foreground': 'oklch(0.988 0.003 106.5)',
      '--card': 'oklch(0.228 0.013 107.4)',
      '--card-foreground': 'oklch(0.988 0.003 106.5)',
      '--popover': 'oklch(0.228 0.013 107.4)',
      '--popover-foreground': 'oklch(0.988 0.003 106.5)',
      '--secondary': 'oklch(0.286 0.016 107.4)',
      '--secondary-foreground': 'oklch(0.988 0.003 106.5)',
      '--muted': 'oklch(0.286 0.016 107.4)',
      '--muted-foreground': 'oklch(0.737 0.021 106.9)',
      '--accent': 'oklch(0.286 0.016 107.4)',
      '--accent-foreground': 'oklch(0.988 0.003 106.5)',
      '--destructive': 'var(--color-red-700)',
      '--destructive-foreground': 'var(--color-white)',
      '--border': 'oklch(1 0 0 / 10%)',
      '--input': 'oklch(1 0 0 / 15%)',
      '--sidebar': 'oklch(0.228 0.013 107.4)',
      '--sidebar-foreground': 'oklch(0.988 0.003 106.5)',
      '--sidebar-accent': 'oklch(0.286 0.016 107.4)',
      '--sidebar-accent-foreground': 'oklch(0.988 0.003 106.5)',
      '--sidebar-border': 'oklch(1 0 0 / 10%)',
      '--primary': 'var(--color-amber-400)',
      '--primary-foreground': 'var(--color-amber-950)',
      '--ring': 'var(--color-amber-400)',
      '--sidebar-primary': 'var(--color-amber-400)',
      '--sidebar-primary-foreground': 'var(--color-amber-950)',
      '--sidebar-ring': 'var(--color-amber-400)',
      '--chart-1': 'var(--color-amber-400)',
      '--chart-2': 'var(--color-lime-400)',
      '--chart-3': 'var(--color-teal-400)',
      '--chart-4': 'var(--color-indigo-400)',
      '--chart-5': 'var(--color-pink-400)',
      '--destructive-subtle': 'var(--color-red-400)',
      '--success-subtle': 'var(--color-green-400)',
      '--warning-subtle': 'var(--color-amber-400)',
      '--core-background-body': 'var(--background)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'var(--border)',
      '--core-band-subtle':
        'color-mix(in oklab, var(--card) 50%, var(--background))',
      '--core-band-strong': 'var(--card)',
      '--core-link': 'var(--brand-400)',
      '--core-surface-invert': 'var(--card)'
    }
  },
  lingon: {
    light: {
      '--brand-50': 'var(--color-rose-50)',
      '--brand-100': 'var(--color-rose-100)',
      '--brand-200': 'var(--color-rose-200)',
      '--brand-300': 'var(--color-rose-300)',
      '--brand-400': 'var(--color-rose-400)',
      '--brand-500': 'var(--color-rose-500)',
      '--brand-600': 'var(--color-rose-600)',
      '--brand-700': 'var(--color-rose-700)',
      '--brand-800': 'var(--color-rose-800)',
      '--brand-900': 'var(--color-rose-900)',
      '--brand-950': 'var(--color-rose-950)',
      '--radius': '0.625rem',
      '--radius-md': 'calc(var(--radius) - 0.125rem)',
      '--background': 'var(--color-white)',
      '--foreground': 'var(--color-stone-950)',
      '--card': 'var(--color-white)',
      '--card-foreground': 'var(--color-stone-950)',
      '--popover': 'var(--color-white)',
      '--popover-foreground': 'var(--color-stone-950)',
      '--secondary': 'var(--color-stone-100)',
      '--secondary-foreground': 'var(--color-stone-900)',
      '--muted': 'var(--color-stone-100)',
      '--muted-foreground': 'var(--color-stone-600)',
      '--accent': 'var(--color-stone-100)',
      '--accent-foreground': 'var(--color-stone-900)',
      '--destructive': 'var(--color-red-600)',
      '--destructive-foreground': 'var(--color-white)',
      '--border': 'var(--color-stone-200)',
      '--input': 'var(--color-stone-200)',
      '--sidebar': 'var(--color-stone-50)',
      '--sidebar-foreground': 'var(--color-stone-950)',
      '--sidebar-accent': 'var(--color-stone-100)',
      '--sidebar-accent-foreground': 'var(--color-stone-900)',
      '--sidebar-border': 'var(--color-stone-200)',
      '--primary': 'var(--color-rose-700)',
      '--primary-foreground': 'var(--color-white)',
      '--ring': 'var(--color-rose-700)',
      '--sidebar-primary': 'var(--color-rose-700)',
      '--sidebar-primary-foreground': 'var(--color-white)',
      '--sidebar-ring': 'var(--color-rose-700)',
      '--chart-1': 'var(--color-rose-600)',
      '--chart-2': 'var(--color-yellow-600)',
      '--chart-3': 'var(--color-emerald-600)',
      '--chart-4': 'var(--color-sky-600)',
      '--chart-5': 'var(--color-purple-600)',
      '--destructive-subtle': 'var(--color-red-700)',
      '--success-subtle': 'var(--color-green-700)',
      '--warning-subtle': 'var(--color-amber-700)',
      '--core-font-mono':
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
      '--core-action-btn-foreground': 'var(--muted-foreground)',
      '--core-action-btn-foreground-hover': 'var(--foreground)',
      '--core-action-btn-background': 'var(--background)',
      '--core-action-btn-track': 'var(--muted)',
      '--core-action-btn-border': 'var(--border)',
      '--core-action-btn-border-hover': 'var(--border)',
      '--core-action-btn-icon-fill': 'var(--muted)',
      '--core-action-btn-shadow': 'transparent',
      '--core-header': 'var(--foreground)',
      '--core-headline': 'var(--foreground)',
      '--core-interactive': 'var(--brand-400)',
      '--core-navbar': 'var(--background)',
      '--core-navbar-border': 'var(--border)',
      '--core-navbar-shadow': 'transparent',
      '--core-nav-link': 'var(--foreground)',
      '--core-nav-link-active': 'var(--primary)',
      '--core-nav-link-hover': 'var(--primary)',
      '--core-text': 'var(--foreground)',
      '--body': 'var(--foreground)',
      '--bold': 'var(--foreground)',
      '--bullets': 'var(--primary)',
      '--captions': 'var(--muted-foreground)',
      '--code': 'var(--foreground)',
      '--code-bg': 'var(--muted)',
      '--counters': 'var(--primary)',
      '--headings': 'var(--foreground)',
      '--hr': 'var(--border)',
      '--links': 'var(--core-link)',
      '--links-hover': 'var(--core-link)',
      '--pre-bg': 'var(--secondary)',
      '--pre-border': 'var(--border)',
      '--pre-code': 'var(--foreground)',
      '--quote-borders': 'var(--border)',
      '--td-borders': 'var(--border)',
      '--th-borders': 'var(--border)',
      '--underline': 'var(--core-link)',
      '--underline-hover': 'var(--core-link)',
      '--core-background-body': 'var(--background)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'var(--border)',
      '--core-sheet-edge': 'transparent',
      '--core-band-reach': 'calc(50% - 50vw)',
      '--core-band-subtle': 'var(--muted)',
      '--core-band-strong': 'var(--card)',
      '--core-font-body': 'Inter Variable, Inter, sans-serif',
      '--core-font-heading': 'Inter Variable, Inter, sans-serif',
      '--core-link': 'var(--brand-700)',
      '--core-surface-invert': 'var(--color-stone-900)'
    },
    dark: {
      '--background': 'var(--color-stone-950)',
      '--foreground': 'var(--color-stone-50)',
      '--card': 'var(--color-stone-900)',
      '--card-foreground': 'var(--color-stone-50)',
      '--popover': 'var(--color-stone-900)',
      '--popover-foreground': 'var(--color-stone-50)',
      '--secondary': 'var(--color-stone-800)',
      '--secondary-foreground': 'var(--color-stone-50)',
      '--muted': 'var(--color-stone-800)',
      '--muted-foreground': 'var(--color-stone-400)',
      '--accent': 'var(--color-stone-800)',
      '--accent-foreground': 'var(--color-stone-50)',
      '--destructive': 'var(--color-red-700)',
      '--destructive-foreground': 'var(--color-white)',
      '--border': 'oklch(1 0 0 / 10%)',
      '--input': 'oklch(1 0 0 / 15%)',
      '--sidebar': 'var(--color-stone-900)',
      '--sidebar-foreground': 'var(--color-stone-50)',
      '--sidebar-accent': 'var(--color-stone-800)',
      '--sidebar-accent-foreground': 'var(--color-stone-50)',
      '--sidebar-border': 'oklch(1 0 0 / 10%)',
      '--primary': 'var(--color-rose-400)',
      '--primary-foreground': 'var(--color-rose-950)',
      '--ring': 'var(--color-rose-400)',
      '--sidebar-primary': 'var(--color-rose-400)',
      '--sidebar-primary-foreground': 'var(--color-rose-950)',
      '--sidebar-ring': 'var(--color-rose-400)',
      '--chart-1': 'var(--color-rose-400)',
      '--chart-2': 'var(--color-yellow-400)',
      '--chart-3': 'var(--color-emerald-400)',
      '--chart-4': 'var(--color-sky-400)',
      '--chart-5': 'var(--color-purple-400)',
      '--destructive-subtle': 'var(--color-red-400)',
      '--success-subtle': 'var(--color-green-400)',
      '--warning-subtle': 'var(--color-amber-400)',
      '--core-background-body': 'var(--background)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'var(--border)',
      '--core-band-subtle':
        'color-mix(in oklab, var(--card) 50%, var(--background))',
      '--core-band-strong': 'var(--card)',
      '--core-link': 'var(--brand-400)',
      '--core-surface-invert': 'var(--card)'
    }
  },
  granite: {
    light: {
      '--brand-50': 'var(--color-slate-50)',
      '--brand-100': 'var(--color-slate-100)',
      '--brand-200': 'var(--color-slate-200)',
      '--brand-300': 'var(--color-slate-300)',
      '--brand-400': 'var(--color-slate-400)',
      '--brand-500': 'var(--color-slate-500)',
      '--brand-600': 'var(--color-slate-600)',
      '--brand-700': 'var(--color-slate-700)',
      '--brand-800': 'var(--color-slate-800)',
      '--brand-900': 'var(--color-slate-900)',
      '--brand-950': 'var(--color-slate-950)',
      '--radius': '0.125rem',
      '--radius-md': 'calc(var(--radius) - 0.125rem)',
      '--background': 'var(--color-white)',
      '--foreground': 'var(--color-zinc-950)',
      '--card': 'var(--color-white)',
      '--card-foreground': 'var(--color-zinc-950)',
      '--popover': 'var(--color-white)',
      '--popover-foreground': 'var(--color-zinc-950)',
      '--secondary': 'var(--color-zinc-100)',
      '--secondary-foreground': 'var(--color-zinc-900)',
      '--muted': 'var(--color-zinc-100)',
      '--muted-foreground': 'var(--color-zinc-600)',
      '--accent': 'var(--color-zinc-100)',
      '--accent-foreground': 'var(--color-zinc-900)',
      '--destructive': 'var(--color-red-600)',
      '--destructive-foreground': 'var(--color-white)',
      '--border': 'var(--color-zinc-200)',
      '--input': 'var(--color-zinc-200)',
      '--sidebar': 'var(--color-zinc-50)',
      '--sidebar-foreground': 'var(--color-zinc-950)',
      '--sidebar-accent': 'var(--color-zinc-100)',
      '--sidebar-accent-foreground': 'var(--color-zinc-900)',
      '--sidebar-border': 'var(--color-zinc-200)',
      '--primary': 'var(--color-zinc-900)',
      '--primary-foreground': 'var(--color-zinc-50)',
      '--ring': 'var(--color-zinc-500)',
      '--sidebar-primary': 'var(--color-zinc-900)',
      '--sidebar-primary-foreground': 'var(--color-zinc-50)',
      '--sidebar-ring': 'var(--color-zinc-500)',
      '--chart-1': 'var(--color-zinc-300)',
      '--chart-2': 'var(--color-zinc-500)',
      '--chart-3': 'var(--color-zinc-600)',
      '--chart-4': 'var(--color-zinc-700)',
      '--chart-5': 'var(--color-zinc-800)',
      '--destructive-subtle': 'var(--color-red-700)',
      '--success-subtle': 'var(--color-green-700)',
      '--warning-subtle': 'var(--color-amber-700)',
      '--core-font-mono':
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
      '--core-action-btn-foreground': 'var(--muted-foreground)',
      '--core-action-btn-foreground-hover': 'var(--foreground)',
      '--core-action-btn-background': 'var(--background)',
      '--core-action-btn-track': 'var(--muted)',
      '--core-action-btn-border': 'var(--border)',
      '--core-action-btn-border-hover': 'var(--border)',
      '--core-action-btn-icon-fill': 'var(--muted)',
      '--core-action-btn-shadow': 'transparent',
      '--core-header': 'var(--foreground)',
      '--core-headline': 'var(--foreground)',
      '--core-interactive': 'var(--brand-400)',
      '--core-navbar': 'var(--background)',
      '--core-navbar-border': 'var(--border)',
      '--core-navbar-shadow': 'transparent',
      '--core-nav-link': 'var(--foreground)',
      '--core-nav-link-active': 'var(--primary)',
      '--core-nav-link-hover': 'var(--primary)',
      '--core-text': 'var(--foreground)',
      '--body': 'var(--foreground)',
      '--bold': 'var(--foreground)',
      '--bullets': 'var(--primary)',
      '--captions': 'var(--muted-foreground)',
      '--code': 'var(--foreground)',
      '--code-bg': 'var(--muted)',
      '--counters': 'var(--primary)',
      '--headings': 'var(--foreground)',
      '--hr': 'var(--border)',
      '--links': 'var(--core-link)',
      '--links-hover': 'var(--core-link)',
      '--pre-bg': 'var(--secondary)',
      '--pre-border': 'var(--border)',
      '--pre-code': 'var(--foreground)',
      '--quote-borders': 'var(--border)',
      '--td-borders': 'var(--border)',
      '--th-borders': 'var(--border)',
      '--underline': 'var(--core-link)',
      '--underline-hover': 'var(--core-link)',
      '--core-background-body': 'var(--background)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'var(--border)',
      '--core-sheet-edge': 'transparent',
      '--core-band-reach': 'calc(50% - 50vw)',
      '--core-band-subtle': 'var(--muted)',
      '--core-band-strong': 'var(--card)',
      '--core-font-body':
        'ui-sans-serif, system-ui, sans-serif, Apple Color Emoji, Segoe UI Emoji',
      '--core-font-heading':
        'ui-sans-serif, system-ui, sans-serif, Apple Color Emoji, Segoe UI Emoji',
      '--core-link': 'var(--primary)',
      '--core-surface-invert': 'var(--color-zinc-900)'
    },
    dark: {
      '--background': 'var(--color-zinc-950)',
      '--foreground': 'var(--color-zinc-50)',
      '--card': 'var(--color-zinc-900)',
      '--card-foreground': 'var(--color-zinc-50)',
      '--popover': 'var(--color-zinc-900)',
      '--popover-foreground': 'var(--color-zinc-50)',
      '--secondary': 'var(--color-zinc-800)',
      '--secondary-foreground': 'var(--color-zinc-50)',
      '--muted': 'var(--color-zinc-800)',
      '--muted-foreground': 'var(--color-zinc-400)',
      '--accent': 'var(--color-zinc-800)',
      '--accent-foreground': 'var(--color-zinc-50)',
      '--destructive': 'var(--color-red-700)',
      '--destructive-foreground': 'var(--color-white)',
      '--border': 'oklch(1 0 0 / 10%)',
      '--input': 'oklch(1 0 0 / 15%)',
      '--sidebar': 'var(--color-zinc-900)',
      '--sidebar-foreground': 'var(--color-zinc-50)',
      '--sidebar-accent': 'var(--color-zinc-800)',
      '--sidebar-accent-foreground': 'var(--color-zinc-50)',
      '--sidebar-border': 'oklch(1 0 0 / 10%)',
      '--primary': 'var(--color-zinc-200)',
      '--primary-foreground': 'var(--color-zinc-900)',
      '--ring': 'var(--color-zinc-500)',
      '--sidebar-primary': 'var(--color-zinc-200)',
      '--sidebar-primary-foreground': 'var(--color-zinc-900)',
      '--sidebar-ring': 'var(--color-zinc-500)',
      '--chart-1': 'var(--color-zinc-300)',
      '--chart-2': 'var(--color-zinc-500)',
      '--chart-3': 'var(--color-zinc-600)',
      '--chart-4': 'var(--color-zinc-700)',
      '--chart-5': 'var(--color-zinc-800)',
      '--destructive-subtle': 'var(--color-red-400)',
      '--success-subtle': 'var(--color-green-400)',
      '--warning-subtle': 'var(--color-amber-400)',
      '--core-background-body': 'var(--background)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'var(--border)',
      '--core-band-subtle':
        'color-mix(in oklab, var(--card) 50%, var(--background))',
      '--core-band-strong': 'var(--card)',
      '--core-link': 'var(--primary)',
      '--core-surface-invert': 'var(--card)'
    }
  },
  aurora: {
    light: {
      '--brand-50': 'var(--color-emerald-50)',
      '--brand-100': 'var(--color-emerald-100)',
      '--brand-200': 'var(--color-emerald-200)',
      '--brand-300': 'var(--color-emerald-300)',
      '--brand-400': 'var(--color-emerald-400)',
      '--brand-500': 'var(--color-emerald-500)',
      '--brand-600': 'var(--color-emerald-600)',
      '--brand-700': 'var(--color-emerald-700)',
      '--brand-800': 'var(--color-emerald-800)',
      '--brand-900': 'var(--color-emerald-900)',
      '--brand-950': 'var(--color-emerald-950)',
      '--radius': '0.75rem',
      '--radius-md': 'calc(var(--radius) - 0.125rem)',
      '--background': 'var(--color-white)',
      '--foreground': 'var(--color-slate-950)',
      '--card': 'var(--color-white)',
      '--card-foreground': 'var(--color-slate-950)',
      '--popover': 'var(--color-white)',
      '--popover-foreground': 'var(--color-slate-950)',
      '--secondary': 'var(--color-slate-100)',
      '--secondary-foreground': 'var(--color-slate-900)',
      '--muted': 'var(--color-slate-100)',
      '--muted-foreground': 'var(--color-slate-600)',
      '--accent': 'var(--color-slate-100)',
      '--accent-foreground': 'var(--color-slate-900)',
      '--destructive': 'var(--color-red-600)',
      '--destructive-foreground': 'var(--color-white)',
      '--border': 'var(--color-slate-200)',
      '--input': 'var(--color-slate-200)',
      '--sidebar': 'var(--color-slate-50)',
      '--sidebar-foreground': 'var(--color-slate-950)',
      '--sidebar-accent': 'var(--color-slate-100)',
      '--sidebar-accent-foreground': 'var(--color-slate-900)',
      '--sidebar-border': 'var(--color-slate-200)',
      '--primary': 'var(--color-emerald-700)',
      '--primary-foreground': 'var(--color-white)',
      '--ring': 'var(--color-emerald-700)',
      '--sidebar-primary': 'var(--color-emerald-700)',
      '--sidebar-primary-foreground': 'var(--color-white)',
      '--sidebar-ring': 'var(--color-emerald-700)',
      '--chart-1': 'var(--color-emerald-600)',
      '--chart-2': 'var(--color-sky-600)',
      '--chart-3': 'var(--color-purple-600)',
      '--chart-4': 'var(--color-rose-600)',
      '--chart-5': 'var(--color-yellow-600)',
      '--destructive-subtle': 'var(--color-red-700)',
      '--success-subtle': 'var(--color-green-700)',
      '--warning-subtle': 'var(--color-amber-700)',
      '--core-font-mono':
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
      '--core-action-btn-foreground': 'var(--muted-foreground)',
      '--core-action-btn-foreground-hover': 'var(--foreground)',
      '--core-action-btn-background': 'var(--background)',
      '--core-action-btn-track': 'var(--muted)',
      '--core-action-btn-border': 'var(--border)',
      '--core-action-btn-border-hover': 'var(--border)',
      '--core-action-btn-icon-fill': 'var(--muted)',
      '--core-action-btn-shadow': 'transparent',
      '--core-header': 'var(--foreground)',
      '--core-headline': 'var(--foreground)',
      '--core-interactive': 'var(--brand-400)',
      '--core-navbar': 'var(--background)',
      '--core-navbar-border': 'var(--border)',
      '--core-navbar-shadow': 'transparent',
      '--core-nav-link': 'var(--foreground)',
      '--core-nav-link-active': 'var(--primary)',
      '--core-nav-link-hover': 'var(--primary)',
      '--core-text': 'var(--foreground)',
      '--body': 'var(--foreground)',
      '--bold': 'var(--foreground)',
      '--bullets': 'var(--primary)',
      '--captions': 'var(--muted-foreground)',
      '--code': 'var(--foreground)',
      '--code-bg': 'var(--muted)',
      '--counters': 'var(--primary)',
      '--headings': 'var(--foreground)',
      '--hr': 'var(--border)',
      '--links': 'var(--core-link)',
      '--links-hover': 'var(--core-link)',
      '--pre-bg': 'var(--secondary)',
      '--pre-border': 'var(--border)',
      '--pre-code': 'var(--foreground)',
      '--quote-borders': 'var(--border)',
      '--td-borders': 'var(--border)',
      '--th-borders': 'var(--border)',
      '--underline': 'var(--core-link)',
      '--underline-hover': 'var(--core-link)',
      '--core-background-body': 'var(--color-slate-50)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'var(--color-slate-100)',
      '--core-sheet-edge': 'var(--core-content-border)',
      '--core-band-reach': '0px',
      '--core-band-subtle': 'var(--muted)',
      '--core-band-strong': 'var(--card)',
      '--core-font-body': 'Inter Variable, Inter, sans-serif',
      '--core-font-heading': 'Inter Variable, Inter, sans-serif',
      '--core-link': 'var(--brand-700)',
      '--core-surface-invert': 'var(--color-slate-900)'
    },
    dark: {
      '--background': 'var(--color-slate-950)',
      '--foreground': 'var(--color-slate-50)',
      '--card': 'var(--color-slate-900)',
      '--card-foreground': 'var(--color-slate-50)',
      '--popover': 'var(--color-slate-900)',
      '--popover-foreground': 'var(--color-slate-50)',
      '--secondary': 'var(--color-slate-800)',
      '--secondary-foreground': 'var(--color-slate-50)',
      '--muted': 'var(--color-slate-800)',
      '--muted-foreground': 'var(--color-slate-400)',
      '--accent': 'var(--color-slate-800)',
      '--accent-foreground': 'var(--color-slate-50)',
      '--destructive': 'var(--color-red-700)',
      '--destructive-foreground': 'var(--color-white)',
      '--border': 'oklch(1 0 0 / 10%)',
      '--input': 'oklch(1 0 0 / 15%)',
      '--sidebar': 'var(--color-slate-900)',
      '--sidebar-foreground': 'var(--color-slate-50)',
      '--sidebar-accent': 'var(--color-slate-800)',
      '--sidebar-accent-foreground': 'var(--color-slate-50)',
      '--sidebar-border': 'oklch(1 0 0 / 10%)',
      '--primary': 'var(--color-emerald-400)',
      '--primary-foreground': 'var(--color-emerald-950)',
      '--ring': 'var(--color-emerald-400)',
      '--sidebar-primary': 'var(--color-emerald-400)',
      '--sidebar-primary-foreground': 'var(--color-emerald-950)',
      '--sidebar-ring': 'var(--color-emerald-400)',
      '--chart-1': 'var(--color-emerald-400)',
      '--chart-2': 'var(--color-sky-400)',
      '--chart-3': 'var(--color-purple-400)',
      '--chart-4': 'var(--color-rose-400)',
      '--chart-5': 'var(--color-yellow-400)',
      '--destructive-subtle': 'var(--color-red-400)',
      '--success-subtle': 'var(--color-green-400)',
      '--warning-subtle': 'var(--color-amber-400)',
      '--core-background-body': 'var(--background)',
      '--core-background-content': 'var(--card)',
      '--core-content-border': 'var(--border)',
      '--core-band-subtle':
        'color-mix(in oklab, var(--card) 50%, var(--background))',
      '--core-band-strong': 'var(--background)',
      '--core-link': 'var(--brand-400)',
      '--core-surface-invert': 'var(--card)'
    }
  },
  cement: {
    light: {
      '--brand-50': 'var(--color-sky-50)',
      '--brand-100': 'var(--color-sky-100)',
      '--brand-200': 'var(--color-sky-200)',
      '--brand-300': 'var(--color-sky-300)',
      '--brand-400': 'var(--color-sky-400)',
      '--brand-500': 'var(--color-sky-500)',
      '--brand-600': 'var(--color-sky-600)',
      '--brand-700': 'var(--color-sky-700)',
      '--brand-800': 'var(--color-sky-800)',
      '--brand-900': 'var(--color-sky-900)',
      '--brand-950': 'var(--color-sky-950)',
      '--radius': '0.375rem',
      '--radius-md': 'calc(var(--radius) - 0.125rem)',
      '--background': 'var(--color-white)',
      '--foreground': 'oklch(0.147 0.004 49.3)',
      '--card': 'var(--color-white)',
      '--card-foreground': 'oklch(0.147 0.004 49.3)',
      '--popover': 'var(--color-white)',
      '--popover-foreground': 'oklch(0.147 0.004 49.3)',
      '--secondary': 'oklch(0.96 0.002 17.2)',
      '--secondary-foreground': 'oklch(0.214 0.009 43.1)',
      '--muted': 'oklch(0.96 0.002 17.2)',
      '--muted-foreground': 'oklch(0.438 0.017 39.3)',
      '--accent': 'oklch(0.96 0.002 17.2)',
      '--accent-foreground': 'oklch(0.214 0.009 43.1)',
      '--destructive': 'var(--color-red-600)',
      '--destructive-foreground': 'var(--color-white)',
      '--border': 'oklch(0.922 0.005 34.3)',
      '--input': 'oklch(0.922 0.005 34.3)',
      '--sidebar': 'oklch(0.986 0.002 67.8)',
      '--sidebar-foreground': 'oklch(0.147 0.004 49.3)',
      '--sidebar-accent': 'oklch(0.96 0.002 17.2)',
      '--sidebar-accent-foreground': 'oklch(0.214 0.009 43.1)',
      '--sidebar-border': 'oklch(0.922 0.005 34.3)',
      '--primary': 'var(--color-sky-700)',
      '--primary-foreground': 'var(--color-white)',
      '--ring': 'var(--color-sky-700)',
      '--sidebar-primary': 'var(--color-sky-700)',
      '--sidebar-primary-foreground': 'var(--color-white)',
      '--sidebar-ring': 'var(--color-sky-700)',
      '--chart-1': 'var(--color-sky-600)',
      '--chart-2': 'var(--color-lime-600)',
      '--chart-3': 'var(--color-amber-400)',
      '--chart-4': 'var(--color-orange-500)',
      '--chart-5': 'var(--color-taupe-500)',
      '--destructive-subtle': 'var(--color-red-700)',
      '--success-subtle': 'var(--color-green-700)',
      '--warning-subtle': 'var(--color-amber-700)',
      '--core-font-mono':
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
      '--core-action-btn-foreground': 'var(--muted-foreground)',
      '--core-action-btn-foreground-hover': 'var(--foreground)',
      '--core-action-btn-background': 'var(--background)',
      '--core-action-btn-track': 'var(--muted)',
      '--core-action-btn-border': 'var(--border)',
      '--core-action-btn-border-hover': 'var(--border)',
      '--core-action-btn-icon-fill': 'var(--muted)',
      '--core-action-btn-shadow': 'transparent',
      '--core-header': 'var(--foreground)',
      '--core-headline': 'var(--foreground)',
      '--core-interactive': 'var(--brand-400)',
      '--core-navbar': 'var(--background)',
      '--core-navbar-border': 'var(--border)',
      '--core-navbar-shadow': 'transparent',
      '--core-nav-link': 'var(--foreground)',
      '--core-nav-link-active': 'var(--primary)',
      '--core-nav-link-hover': 'var(--primary)',
      '--core-text': 'var(--foreground)',
      '--body': 'var(--foreground)',
      '--bold': 'var(--foreground)',
      '--bullets': 'var(--primary)',
      '--captions': 'var(--muted-foreground)',
      '--code': 'var(--foreground)',
      '--code-bg': 'var(--muted)',
      '--counters': 'var(--primary)',
      '--headings': 'var(--foreground)',
      '--hr': 'var(--border)',
      '--links': 'var(--core-link)',
      '--links-hover': 'var(--core-link)',
      '--pre-bg': 'var(--secondary)',
      '--pre-border': 'var(--border)',
      '--pre-code': 'var(--foreground)',
      '--quote-borders': 'var(--border)',
      '--td-borders': 'var(--border)',
      '--th-borders': 'var(--border)',
      '--underline': 'var(--core-link)',
      '--underline-hover': 'var(--core-link)',
      '--core-background-body': 'var(--background)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'var(--border)',
      '--core-sheet-edge': 'transparent',
      '--core-band-reach': 'calc(50% - 50vw)',
      '--core-band-subtle': 'var(--muted)',
      '--core-band-strong': 'var(--card)',
      '--core-font-body': 'Inter Variable, Inter, sans-serif',
      '--core-font-heading': 'Inter Variable, Inter, sans-serif',
      '--core-link': 'var(--brand-700)',
      '--core-surface-invert': 'oklch(0.214 0.009 43.1)'
    },
    dark: {
      '--background': 'oklch(0.147 0.004 49.3)',
      '--foreground': 'oklch(0.986 0.002 67.8)',
      '--card': 'oklch(0.214 0.009 43.1)',
      '--card-foreground': 'oklch(0.986 0.002 67.8)',
      '--popover': 'oklch(0.214 0.009 43.1)',
      '--popover-foreground': 'oklch(0.986 0.002 67.8)',
      '--secondary': 'oklch(0.268 0.011 36.5)',
      '--secondary-foreground': 'oklch(0.986 0.002 67.8)',
      '--muted': 'oklch(0.268 0.011 36.5)',
      '--muted-foreground': 'oklch(0.714 0.014 41.2)',
      '--accent': 'oklch(0.268 0.011 36.5)',
      '--accent-foreground': 'oklch(0.986 0.002 67.8)',
      '--destructive': 'var(--color-red-700)',
      '--destructive-foreground': 'var(--color-white)',
      '--border': 'oklch(1 0 0 / 10%)',
      '--input': 'oklch(1 0 0 / 15%)',
      '--sidebar': 'oklch(0.214 0.009 43.1)',
      '--sidebar-foreground': 'oklch(0.986 0.002 67.8)',
      '--sidebar-accent': 'oklch(0.268 0.011 36.5)',
      '--sidebar-accent-foreground': 'oklch(0.986 0.002 67.8)',
      '--sidebar-border': 'oklch(1 0 0 / 10%)',
      '--primary': 'var(--color-sky-400)',
      '--primary-foreground': 'var(--color-sky-950)',
      '--ring': 'var(--color-sky-400)',
      '--sidebar-primary': 'var(--color-sky-400)',
      '--sidebar-primary-foreground': 'var(--color-sky-950)',
      '--sidebar-ring': 'var(--color-sky-400)',
      '--chart-1': 'var(--color-sky-400)',
      '--chart-2': 'var(--color-lime-400)',
      '--chart-3': 'var(--color-amber-300)',
      '--chart-4': 'var(--color-orange-400)',
      '--chart-5': 'var(--color-taupe-400)',
      '--destructive-subtle': 'var(--color-red-400)',
      '--success-subtle': 'var(--color-green-400)',
      '--warning-subtle': 'var(--color-amber-400)',
      '--core-background-body': 'var(--background)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'var(--border)',
      '--core-band-subtle':
        'color-mix(in oklab, var(--card) 50%, var(--background))',
      '--core-band-strong': 'var(--card)',
      '--core-link': 'var(--brand-400)',
      '--core-surface-invert': 'var(--card)'
    }
  }
};
